CREATE TABLE IF NOT EXISTS rfqs (
  id VARCHAR(20) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  deadline VARCHAR(50) NOT NULL DEFAULT 'TBD',
  value DECIMAL(15, 2) NOT NULL DEFAULT 0,
  description TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Draft',
  awarded_supplier VARCHAR(255) NULL,
  awarded_bid_id VARCHAR(20) NULL,
  awarded_amount DECIMAL(15, 2) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bids (
  id VARCHAR(20) NOT NULL PRIMARY KEY,
  rfq_id VARCHAR(20) NOT NULL,
  supplier VARCHAR(255) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  delivery VARCHAR(100) NOT NULL DEFAULT '30 days',
  warranty VARCHAR(100) NOT NULL DEFAULT '12 months',
  rating DECIMAL(4, 2) NOT NULL DEFAULT 4.70,
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bids_rfq FOREIGN KEY (rfq_id) REFERENCES rfqs (id) ON DELETE CASCADE,
  UNIQUE KEY uq_bid_supplier (rfq_id, supplier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
